/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;//database connection
import javax.swing.JOptionPane;//alert messages
import javax.swing.table.DefaultTableModel;//table

public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        this.setLocationRelativeTo(null);//setting jframe into center
        display();//call the display function that contains the display of the all users, all admins,....
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        container1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dashboardDropDown = new javax.swing.JComboBox<>();
        productsDropDown = new javax.swing.JComboBox<>();
        showRequestsDropDown = new javax.swing.JComboBox<>();
        showProductArchivedDropDown = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        signout = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        requests = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        approvedOrders = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        users = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        admins = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        disabledUsers = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        disabledAdmins = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        orders = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        sales = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        stocks = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(685, 490));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 450));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container1.setBackground(new java.awt.Color(10, 117, 240));
        container1.setPreferredSize(new java.awt.Dimension(670, 487));
        container1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("_____________________");
        container1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Passerelles Numeriques.org");
        container1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("___________");
        container1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 434, 90, 30));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Administrator");
        container1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, -1));
        container1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, 40));

        adminName.setBackground(new java.awt.Color(255, 255, 255));
        adminName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminName.setForeground(new java.awt.Color(255, 255, 255));
        adminName.setText("Name");
        container1.add(adminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  Admin");
        container1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 65, 50, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("• online");
        container1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        searchField.setName(""); // NOI18N
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        container1.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 98, 25));

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setIcon(new javax.swing.ImageIcon("C:\\Users\\2ndyrGroupA\\Documents\\NetBeansProjects\\javafinal\\Images\\rsz_1search.png")); // NOI18N
        search.setMaximumSize(new java.awt.Dimension(50, 29));
        search.setMinimumSize(new java.awt.Dimension(50, 29));
        search.setPreferredSize(new java.awt.Dimension(50, 20));
        container1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 25, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("General");
        container1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, -1));

        dashboardDropDown.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dashboardDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dashboard", "Users", "Admins", "Disabled Users", "Disabled Admins" }));
        dashboardDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardDropDownActionPerformed(evt);
            }
        });
        container1.add(dashboardDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 125, -1));

        productsDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Products", "Orders" }));
        productsDropDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsDropDownMouseClicked(evt);
            }
        });
        productsDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsDropDownActionPerformed(evt);
            }
        });
        container1.add(productsDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 125, -1));

        showRequestsDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Show requests" }));
        showRequestsDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRequestsDropDownActionPerformed(evt);
            }
        });
        container1.add(showRequestsDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 125, -1));

        showProductArchivedDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product Archived" }));
        showProductArchivedDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProductArchivedDropDownActionPerformed(evt);
            }
        });
        container1.add(showProductArchivedDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 125, -1));

        jButton2.setText("About us");
        container1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 82, -1));

        signout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setText("Sign out");
        signout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signoutMouseClicked(evt);
            }
        });
        container1.add(signout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jPanel1.add(container1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 145, 490));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("DASHBOARD");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 175, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("   User Product Requests");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        requests.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        requests.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(requests, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(requests, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 150, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("   Orders Approved");

        approvedOrders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        approvedOrders.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(approvedOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(approvedOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("     Total Users");

        users.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        users.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(users, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("  Total Admins");

        admins.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        admins.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(admins, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(admins, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("    Total Disabled Users");

        disabledUsers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        disabledUsers.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(disabledUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(disabledUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, 50));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText(" Total Disabled Admins");

        disabledAdmins.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        disabledAdmins.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(disabledAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(disabledAdmins, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("            Orders ");

        orders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        orders.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(orders, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(orders, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("      Total Sales");

        sales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sales.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(sales, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(sales, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 260, 50));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Total Products Stocks");

        stocks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stocks.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(stocks, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(stocks, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30))
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("(Store Statistics)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void dashboardDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardDropDownActionPerformed
        if (this.dashboardDropDown.getSelectedIndex() == 0) {//when selecting the index zero in dashboard combobox,
            new AdminPage().setVisible(true);//set the page into admin page
            this.setVisible(false);//set the visibility of this page as false
        }
        if (this.dashboardDropDown.getSelectedIndex() == 1) {//when selecting the index 1 in dashboard combobox,
            new Users().setVisible(true);//set the page into users page
            this.setVisible(false);//set the visibility of this page as false
        }
        if (this.dashboardDropDown.getSelectedIndex() == 2) {
            new Admins().setVisible(true);
            this.setVisible(false);
        }
        if (this.dashboardDropDown.getSelectedIndex() == 3) {
            new DisabledUsers().setVisible(true);
            this.setVisible(false);
        }
        if (this.dashboardDropDown.getSelectedIndex() == 4) {
            new DisabledAdmins().setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_dashboardDropDownActionPerformed

    private void productsDropDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsDropDownMouseClicked

    }//GEN-LAST:event_productsDropDownMouseClicked

    private void productsDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsDropDownActionPerformed
        if (this.productsDropDown.getSelectedIndex() == 0) {
            new Products().setVisible(true);
            this.setVisible(false);
        }
        if (this.productsDropDown.getSelectedIndex() == 1) {
            new Orders().setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_productsDropDownActionPerformed

    private void showRequestsDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRequestsDropDownActionPerformed
        if (this.showRequestsDropDown.getSelectedIndex() == 0) {
            new UserProductRequests().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_showRequestsDropDownActionPerformed

    private void showProductArchivedDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showProductArchivedDropDownActionPerformed
        if (this.showProductArchivedDropDown.getSelectedIndex() == 0) {
            new ArchivedProducts().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_showProductArchivedDropDownActionPerformed

    private void signoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMouseClicked
        new AdminLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminName;
    private javax.swing.JLabel admins;
    private javax.swing.JLabel approvedOrders;
    private javax.swing.JPanel container1;
    private javax.swing.JComboBox<String> dashboardDropDown;
    private javax.swing.JLabel disabledAdmins;
    private javax.swing.JLabel disabledUsers;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel orders;
    private javax.swing.JComboBox<String> productsDropDown;
    private javax.swing.JLabel requests;
    private javax.swing.JLabel sales;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> showProductArchivedDropDown;
    private javax.swing.JComboBox<String> showRequestsDropDown;
    private javax.swing.JLabel signout;
    private javax.swing.JLabel stocks;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables

    public void display() {
        //count all users
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javafinal", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `users`");

            int countUsers = 0;
            while (datas.next()) {
                countUsers++;

            }
            String calcUsers = String.valueOf(countUsers);
            users.setText(calcUsers);

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        //count all admins
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javafinal", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `admins`");

            int countAdmins = 0;
            while (datas.next()) {
                countAdmins++;

            }
            String calcAdmins = String.valueOf(countAdmins);
            admins.setText(calcAdmins);

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        //count all disabledusers
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javafinal", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `disabledusers`");

            int countDisabledUsers = 0;
            while (datas.next()) {
                countDisabledUsers++;

            }
            String calcDisabledUsers = String.valueOf(countDisabledUsers);
            disabledUsers.setText(calcDisabledUsers);

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        //count all disabledAdmins
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javafinal", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `disabledadmins`");

            int countDisabledAdmins = 0;
            while (datas.next()) {
                countDisabledAdmins++;

            }
            String calcDisabledAdmins = String.valueOf(countDisabledAdmins);
            disabledAdmins.setText(calcDisabledAdmins);

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        //count all user product requests
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javafinal", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `requestproducts`");

            int countRequestProducts = 0;
            while (datas.next()) {
                countRequestProducts++;

            }
            String calcRequestProducts = String.valueOf(countRequestProducts);
            requests.setText(calcRequestProducts);

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        //count all approved orders
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javafinal", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `approveorders`");

            int countApprovedOrders = 0;
            while (datas.next()) {
                countApprovedOrders++;

            }
            String calcApprovedOrders = String.valueOf(countApprovedOrders);
            approvedOrders.setText(calcApprovedOrders);

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        //count all ordered products
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javafinal", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `orderedproducts`");

            int countOrderedProducts = 0;
            while (datas.next()) {
                countOrderedProducts++;

            }
            String calcOrderedProducts = String.valueOf(countOrderedProducts);
            orders.setText(calcOrderedProducts);

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        //Count total sales
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javafinal", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `approveorders` ");

            int countSales = 0;
            while (datas.next()) {
                countSales += datas.getInt("totalprice");

            }
            String calcSales = String.valueOf(countSales);
            sales.setText(calcSales);

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        //Count total stocks
        //Count total sales
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javafinal", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `products` ");

            int countStocks = 0;
            while (datas.next()) {
                countStocks += datas.getInt("stocks");

            }
            String calcStocks = String.valueOf(countStocks);
            stocks.setText(calcStocks);

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }
}
