/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Admins extends javax.swing.JFrame {
    /**
     *
     */
    public Admins() {
        initComponents();
        this.setLocationRelativeTo(null);
        getdata();
        
    }
    
      public void getdata() {
       int count = 0;
      
       try {
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javafinal", "root", "");
           Statement stmt = con.createStatement();

           ResultSet data = stmt.executeQuery("SELECT * FROM `admins`");
           DefaultTableModel model = (DefaultTableModel) adminTable.getModel();
           while (data.next()) {
              
               count = 1;
               model.addRow(new Object[]{data.getInt("admin_id"), data.getString("firstname"), data.getString("lastname"), data.getString("username"), data.getString("password"), data.getString("status")});

           }

           if (count == 0) {
               JOptionPane.showMessageDialog(null, "No data found!.", "Alert", JOptionPane.WARNING_MESSAGE);
           }
           con.close();
       } catch (Exception e) {
           System.out.println(e.getMessage());
       }

   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        addAdmin = new javax.swing.JButton();
        backToAdminPage = new javax.swing.JLabel();
        disableAdmin = new javax.swing.JButton();
        openAdminAccount = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 480));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 480));

        jPanel2.setBackground(new java.awt.Color(10, 117, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registered Admins");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        adminTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Namel", "Username", "Password", "Status"
            }
        ));
        adminTable.setGridColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(adminTable);

        addAdmin.setBackground(new java.awt.Color(10, 117, 240));
        addAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addAdmin.setForeground(new java.awt.Color(255, 255, 255));
        addAdmin.setText("Add Admin");
        addAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAdminMouseClicked(evt);
            }
        });

        backToAdminPage.setBackground(new java.awt.Color(0, 0, 0));
        backToAdminPage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backToAdminPage.setForeground(new java.awt.Color(10, 117, 240));
        backToAdminPage.setText("Home");
        backToAdminPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToAdminPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToAdminPageMouseClicked(evt);
            }
        });

        disableAdmin.setBackground(new java.awt.Color(10, 117, 240));
        disableAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disableAdmin.setForeground(new java.awt.Color(255, 255, 255));
        disableAdmin.setText("Disable Admin");
        disableAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disableAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableAdminMouseClicked(evt);
            }
        });

        openAdminAccount.setBackground(new java.awt.Color(255, 255, 0));
        openAdminAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        openAdminAccount.setText("Open Admin Account");
        openAdminAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openAdminAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openAdminAccountMouseClicked(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 153, 0));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 51));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addAdmin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backToAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(openAdminAccount)
                        .addGap(18, 18, 18)
                        .addComponent(disableAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backToAdminPage))
                .addGap(2, 2, 2)
                .addComponent(addAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disableAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openAdminAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToAdminPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToAdminPageMouseClicked
        new AdminPage().setVisible(true);
    }//GEN-LAST:event_backToAdminPageMouseClicked

    private void addAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAdminMouseClicked
        new AddAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addAdminMouseClicked

    private void disableAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableAdminMouseClicked
        DefaultTableModel model = (DefaultTableModel) adminTable.getModel();
        int row = adminTable.getSelectedRow();
         try{
            JFrame frame = new JFrame("Disable Admin");
            if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to disable this as Admin?","Super Admin Message", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
               int identify = Integer.parseInt(model.getValueAt(row, 0).toString());
               String firstname = (model.getValueAt(row, 1).toString());
               String lastname= (model.getValueAt(row, 2).toString());
               String username = (model.getValueAt(row, 3).toString());
               String password = (model.getValueAt(row, 4).toString());
               
                 
               
               Class.forName("com.mysql.jdbc.Driver");
               Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javafinal","root","");
               PreparedStatement stmt = con.prepareStatement ("INSERT INTO `disabledadmins` (`admin_id`,`firstname`, `lastname`, `username`, `password`) VALUES (default,?,?,?,?)");
               PreparedStatement stmt1 = con.prepareStatement("DELETE FROM admins WHERE admin_id =?");
               
               
               stmt.setString(1,firstname);
               stmt.setString(2,lastname);
               stmt.setString(3,username);
               stmt.setString(4,password);
        
               stmt.executeUpdate();
                
               stmt1.setInt(1,identify);
               stmt1.executeUpdate();
               model.removeRow(row);
               
               stmt1.executeUpdate();
              
                     
               JOptionPane.showMessageDialog(null, "Successfully Disabled as Admin.", "Message from MySQL", JOptionPane.INFORMATION_MESSAGE);
               
               new DisabledAdmins().setVisible(true);
               this.setVisible(false);
               
               JOptionPane.showMessageDialog(null, "New data added.", "Message from MySQL", JOptionPane.INFORMATION_MESSAGE);
               
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Message from MySQL", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_disableAdminMouseClicked

    private void openAdminAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openAdminAccountMouseClicked
        new OpenAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_openAdminAccountMouseClicked

     UpdateAdmin UpdateAdmin = new UpdateAdmin();
     
    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) adminTable.getModel();
        int row = adminTable.getSelectedRow();
        
        String id = model.getValueAt(row, 0).toString();
        String firstname = model.getValueAt(row, 1).toString();
        String lastname = model.getValueAt(row, 2).toString();
        String username = model.getValueAt(row, 3).toString();
        String password = model.getValueAt(row, 4).toString();

        UpdateAdmin .pack();
        UpdateAdmin.getDefaultCloseOperation();
        UpdateAdmin.admin_id.setText(id);
        UpdateAdmin.inputFirstname.setText(firstname);
        UpdateAdmin.inputLastname.setText(lastname);
        UpdateAdmin.inputUsername.setText(username);
        UpdateAdmin.inputPassword.setText(password);

        UpdateAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updateBtnMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) adminTable.getModel();
        int row = adminTable.getSelectedRow();

        try{

            JFrame frame = new JFrame ("Delete");
            if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to delete?","Admin Message", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
                int identify = Integer.parseInt(model.getValueAt(row, 0).toString());
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javafinal","root","");
                PreparedStatement stmt = con.prepareStatement("DELETE FROM admins WHERE admin_id =?");
                stmt.setInt(1,identify);
                stmt.executeUpdate();
                model.removeRow(row);
                
                JOptionPane.showMessageDialog(null, "Successfully Deleted.", "Message from MySQL", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdmin;
    public static javax.swing.JTable adminTable;
    private javax.swing.JLabel backToAdminPage;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton disableAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton openAdminAccount;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
