/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Shop extends javax.swing.JFrame {

    /**
     * Creates new form Shop
     */
    public Shop() {
        initComponents();
        this.setLocationRelativeTo(null);
        getData();
    }

    public void getData() {
        int count = 0;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javafinal", "root", "");
            Statement stmt = con.createStatement();

            ResultSet data = stmt.executeQuery("SELECT * FROM `products`");
            DefaultTableModel model = (DefaultTableModel) productsTable.getModel();

            while (data.next()) {
                count = 1;
                model.addRow(new Object[]{data.getString("product_id"),data.getString("photo"), data.getString("name"), data.getString("brand"), data.getString("description"), data.getInt("price"), data.getInt("stocks")});
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(null, "No data found!.", "Message from MySQL", JOptionPane.WARNING_MESSAGE);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        requestEditBtn = new javax.swing.JButton();
        buyBtn = new javax.swing.JButton();
        backToUserPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Photo", "Name", "Brand", "Description", "price", "stocks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 590, 340));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Order Now, Pay Later!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        requestEditBtn.setBackground(new java.awt.Color(51, 153, 0));
        requestEditBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        requestEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestEditBtn.setText("Request Edit");
        requestEditBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        requestEditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestEditBtnMouseClicked(evt);
            }
        });
        jPanel1.add(requestEditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 140, 40));

        buyBtn.setBackground(new java.awt.Color(10, 117, 240));
        buyBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buyBtn.setForeground(new java.awt.Color(255, 255, 255));
        buyBtn.setText("Buy");
        buyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBtnMouseClicked(evt);
            }
        });
        buyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(buyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 90, 40));

        backToUserPage.setBackground(new java.awt.Color(0, 0, 0));
        backToUserPage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backToUserPage.setForeground(new java.awt.Color(0, 102, 255));
        backToUserPage.setText("Home");
        backToUserPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToUserPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToUserPageMouseClicked(evt);
            }
        });
        jPanel1.add(backToUserPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 50, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToUserPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToUserPageMouseClicked
        new UserPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backToUserPageMouseClicked

    BuyProcess buy = new BuyProcess();

    private void buyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) productsTable.getModel();
        int row = productsTable.getSelectedRow();

        String id = model.getValueAt(row, 0).toString();
        String product_photo = model.getValueAt(row, 1).toString();
        String product_name = model.getValueAt(row, 2).toString();
        String product_brand = model.getValueAt(row, 3).toString();
        String product_description = model.getValueAt(row, 4).toString();
        String product_price = model.getValueAt(row, 5).toString();
        String product_stocks = model.getValueAt(row, 6).toString();

        buy.pack();
        buy.getDefaultCloseOperation();
        buy.product_id.setText(id);
        buy.photo.setText(product_photo);
        buy.name.setText(product_name);
        buy.brand.setText(product_brand);
        buy.description.setText(product_description);
        buy.price.setText(product_price);
        buy.stocks.setText(product_stocks);

        buy.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_buyBtnMouseClicked

    RequestProcess RequestProcess = new RequestProcess();

    private void requestEditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestEditBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) productsTable.getModel();
        int row = productsTable.getSelectedRow();

        String id = model.getValueAt(row, 0).toString();
        String photo = model.getValueAt(row, 1).toString();
        String name = model.getValueAt(row, 2).toString();
        String brand = model.getValueAt(row, 3).toString();
        String description = model.getValueAt(row, 4).toString();
        String price = model.getValueAt(row, 5).toString();
        String stocks = model.getValueAt(row, 6).toString();
        

        RequestProcess.pack();
        RequestProcess.getDefaultCloseOperation();
        RequestProcess.product_id.setText(id);
        RequestProcess.photo.setText(photo);
        RequestProcess.name.setText(name);
        RequestProcess.brand.setText(brand);
        RequestProcess.description.setText(description);
        RequestProcess.price.setText(price);
        RequestProcess.stocks.setText(stocks);
        
        

        RequestProcess.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_requestEditBtnMouseClicked

    private void buyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backToUserPage;
    private javax.swing.JButton buyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable productsTable;
    private javax.swing.JButton requestEditBtn;
    // End of variables declaration//GEN-END:variables
}
