/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Users extends javax.swing.JFrame {

    /**
     * Creates new form Users
     */
    public Users() {
        initComponents();
        this.setLocationRelativeTo(null);
        getData();
    }
    
    public void getData(){
        int count = 0;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javafinal","root","");
            Statement stmt = con.createStatement();
            
            ResultSet data = stmt.executeQuery("SELECT * FROM `users`");
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            
            while (data.next()){
                
                count = 1;
                model.addRow(new Object[]{data.getInt("user_id"), data.getString("firstname"), data.getString("lastname"), data.getString("username"), data.getString("password"), data.getString("status")});                                                 
            }
            
            if (count == 0){
                 JOptionPane.showMessageDialog(null, "No data found!.", "Alert", JOptionPane.WARNING_MESSAGE);        
            }
            con.close();
            
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        addUser = new javax.swing.JButton();
        backToAdminPage = new javax.swing.JLabel();
        disableUser = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn1 = new javax.swing.JButton();
        openUserAccount1 = new javax.swing.JButton();
        addAsAdmin1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 450));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(10, 117, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registered Users");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 250, 70));

        userTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Username", "Password", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        userTable.setGridColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(userTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 620, 270));

        addUser.setBackground(new java.awt.Color(10, 117, 240));
        addUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addUser.setForeground(new java.awt.Color(255, 255, 255));
        addUser.setText("Add User");
        addUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserMouseClicked(evt);
            }
        });
        jPanel1.add(addUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, 30));

        backToAdminPage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backToAdminPage.setForeground(new java.awt.Color(10, 117, 240));
        backToAdminPage.setText("Home");
        backToAdminPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToAdminPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToAdminPageMouseClicked(evt);
            }
        });
        jPanel1.add(backToAdminPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        disableUser.setBackground(new java.awt.Color(255, 255, 0));
        disableUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disableUser.setText("Disable User");
        disableUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableUserMouseClicked(evt);
            }
        });
        jPanel1.add(disableUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, 30));

        deleteBtn.setBackground(new java.awt.Color(255, 0, 51));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, 30));

        updateBtn1.setBackground(new java.awt.Color(0, 153, 0));
        updateBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateBtn1.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn1.setText("Update");
        updateBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtn1MouseClicked(evt);
            }
        });
        updateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 80, 30));

        openUserAccount1.setBackground(new java.awt.Color(255, 255, 0));
        openUserAccount1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        openUserAccount1.setText("Open User Account");
        openUserAccount1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openUserAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openUserAccount1MouseClicked(evt);
            }
        });
        jPanel1.add(openUserAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 30));

        addAsAdmin1.setBackground(new java.awt.Color(255, 255, 0));
        addAsAdmin1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addAsAdmin1.setText("Add as Admin");
        addAsAdmin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAsAdmin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAsAdmin1MouseClicked(evt);
            }
        });
        jPanel1.add(addAsAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToAdminPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToAdminPageMouseClicked
        new AdminPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backToAdminPageMouseClicked

    private void addUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserMouseClicked
        new AddUser().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addUserMouseClicked
     UpdateUser update = new UpdateUser();
    
   
    
    private void disableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableUserMouseClicked
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        int row = userTable.getSelectedRow();
        try{
            JFrame frame = new JFrame("Disable as User");
            if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to disable him/her as User?","Admin Message", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
               int identify = Integer.parseInt(model.getValueAt(row, 0).toString());
               String firstname = (model.getValueAt(row, 1).toString());
               String lastname= (model.getValueAt(row, 2).toString());
               String username = (model.getValueAt(row, 3).toString());
               String password = (model.getValueAt(row, 4).toString());
               
               
               
               Class.forName("com.mysql.jdbc.Driver");
               Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javafinal","root","");
               PreparedStatement stmt = con.prepareStatement ("INSERT INTO `disabledusers` (`user_id`,`firstname`, `lastname`, `username`, `password`) VALUES (default,?,?,?,?)");
               PreparedStatement stmt1 = con.prepareStatement("DELETE FROM users WHERE user_id =?");
              
               stmt.setString(1,firstname);
               stmt.setString(2,lastname);
               stmt.setString(3,username);
               stmt.setString(4,password);
        
               stmt.executeUpdate();
               
               stmt1.setInt(1,identify);
               stmt1.executeUpdate();
               model.removeRow(row);
               
               JOptionPane.showMessageDialog(null, "Successfully Disabled as User.", "Message from MySQL", JOptionPane.INFORMATION_MESSAGE);
               JOptionPane.showMessageDialog(null, "He/she will be deleted as a user.", "Message from MySQL", JOptionPane.INFORMATION_MESSAGE);
               
               new DisabledUsers().setVisible(true);
               this.setVisible(false);
               
                JOptionPane.showMessageDialog(null, "New data added.", "Message from MySQL", JOptionPane.INFORMATION_MESSAGE);
               
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Alert", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_disableUserMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        int row = userTable.getSelectedRow();
       
       try{
           
           JFrame frame = new JFrame ("Delete");
           if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to delete?","Delete", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
               int identify = Integer.parseInt(model.getValueAt(row, 0).toString());
               Class.forName("com.mysql.jdbc.Driver");
               Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javafinal","root","");
               PreparedStatement stmt = con.prepareStatement("DELETE FROM users WHERE user_id =?");
               stmt.setInt(1,identify);
               stmt.executeUpdate();
               model.removeRow(row);
               
               JOptionPane.showMessageDialog(null, "Successfully Deleted.", "Message from MySQL", JOptionPane.INFORMATION_MESSAGE);
           }
       }catch (Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage(),"Message from MySQL", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void updateBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtn1MouseClicked
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        int row = userTable.getSelectedRow();
        String id = model.getValueAt(row, 0).toString();
        String firstname = model.getValueAt(row, 1).toString();
        String lastname = model.getValueAt(row, 2).toString();
        String username = model.getValueAt(row, 3).toString();
        String password = model.getValueAt(row, 4).toString();
        
        update.pack();
        update.getDefaultCloseOperation();
        update.user_id.setText(id);
        update.inputFirstname.setText(firstname);
        update.inputLastname.setText(lastname);
        update.inputUsername.setText(username);
        update.inputPassword.setText(password);
        
        update.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updateBtn1MouseClicked

    private void updateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtn1ActionPerformed

    private void openUserAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openUserAccount1MouseClicked
        new UserLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_openUserAccount1MouseClicked

    private void addAsAdmin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAsAdmin1MouseClicked
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        int row = userTable.getSelectedRow();
        try{
            JFrame frame = new JFrame("Add as Admin");
            if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to add him/her as Admin?","Admin Message", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
               int identify = Integer.parseInt(model.getValueAt(row, 0).toString());
               String firstname = (model.getValueAt(row, 1).toString());
               String lastname= (model.getValueAt(row, 2).toString());
               String username = (model.getValueAt(row, 3).toString());
               String password = (model.getValueAt(row, 4).toString());
               
               
               
               Class.forName("com.mysql.jdbc.Driver");
               Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javafinal","root","");
               PreparedStatement stmt = con.prepareStatement ("INSERT INTO `admins` (`admin_id`,`firstname`, `lastname`, `username`, `password`) VALUES (default,?,?,?,?)");
               PreparedStatement stmt1 = con.prepareStatement("DELETE FROM users WHERE user_id =?");
               
               
               stmt.setString(1,firstname);
               stmt.setString(2,lastname);
               stmt.setString(3,username);
               stmt.setString(4,password);
        
               stmt.executeUpdate();
                
               stmt1.setInt(1,identify);
               stmt1.executeUpdate();
               model.removeRow(row);
               
               stmt1.executeUpdate();
              
                     
               JOptionPane.showMessageDialog(null, "Successfully Added as Admin.", "Message from MySQL", JOptionPane.INFORMATION_MESSAGE);
               
               new Admins().setVisible(true);
               this.setVisible(false);
               
               JOptionPane.showMessageDialog(null, "New data added.", "Message from MySQL", JOptionPane.INFORMATION_MESSAGE);
               
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Message from MySQL", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addAsAdmin1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAsAdmin1;
    private javax.swing.JButton addUser;
    private javax.swing.JLabel backToAdminPage;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton disableUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton openUserAccount1;
    private javax.swing.JButton updateBtn1;
    public static javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
